//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Script1.rc
//
#define IDR_MENU1                       101
#define IDI_ICON1                       103
#define IDI_ICON2                       104
#define IDR_MENU2                       105
#define IDI_ICON3                       107
#define IDB_BITMAP1                     108
#define IDR_MENU3                       109
#define IDR_MENU4                       110
#define IDD_SIGNON                      111
#define IDB_BITMAP2                     114
#define IDD_DIALOG3                     115
#define IDD_DIALOG4                     116
#define IDD_AWAYMESSAGE                 116
#define IDR_MENU5                       128
#define IDC_TREELISTBOX                 133
#define IDI_ICON4                       138
#define IDR_MENU_TRAY                   141
#define IDR_MENU_MAIN                   142
#define IDR_MENU_CHAT                   143
#define IDR_MENU_DEBUG                  144
#define IDR_MENU_BUDDY                  145
#define IDD_ABOUT                       148
#define IDD_INFO                        149
#define IDD_EDITINFO                    150
#define IDD_ADDBUDDY                    156
#define IDD_ADDGROUP                    157
#define IDD_DIALOG2                     159
#define IDB_BITMAP3                     160
#define IDB_DELBUDDY                    161
#define IDB_ADDBUDDY                    162
#define IDB_ADDGROUP                    163
#define IDB_AWAYMESSAGE                 164
#define IDB_KILLALLWINDOWS              165
#define IDR_MENU_STATUS                 166
#define PROPERTIES                      170
#define PROPERTIES_BUDDYLIST            171
#define PROPERTIES_LOGGING              172
#define PROPERTIES_NETWORK              173
#define PROPERTIES_USER                 174
#define IDD_DIALOG5                     175
#define IDD_CREATECHATROOM              178
#define PROPERTIES_AWAYANDIDLE          179
#define IDC_STATUS_VIEW                 199
#define IDC_TRAY_ICON                   200
#define IDC_BUTTON1                     1005
#define IDC_P_SAVE                      1005
#define IDC_BUTTON2                     1006
#define IDC_EDIT1                       1010
#define IDC_EDIT2                       1011
#define IDC_PASSWORD                    1011
#define IDC_P_PORT                      1011
#define IDC_P_TOCPORT                   1011
#define IDC_COMBO1                      1013
#define IDC_USERNAME                    1013
#define IDC_RADIO1                      1015
#define IDC_RADIO2                      1016
#define IDC_RADIO3                      1017
#define IDC_TREE1                       1018
#define IDC_TAB1                        1019
#define IDC_SAVEPASSWORD                1021
#define IDC_AUTOLOGIN                   1022
#define IDC_SIGNON                      1024
#define IDC_OPTIONS                     1025
#define IDC_STATUS                      1026
#define IDC_SHOWDEBUG                   1027
#define ID_SAVEINFO                     1029
#define ID_CANCELINFO                   1030
#define IDC_RICHEDIT1                   1031
#define IDC_ENABLELOGGING               1032
#define IDC_HTMLVIEW                    1033
#define ID_ADD                          1034
#define IDC_BUTTON3                     1035
#define IDC_BUTTON4                     1036
#define IDC_BUTTON5                     1037
#define IDC_BUTTON6                     1038
#define IDC_BUTTON7                     1039
#define IDC_BUTTON8                     1040
#define IDC_CHECK1                      1041
#define IDC_KEEYBUDDYLISTONTOP          1041
#define IDC_P_HOST                      1042
#define IDC_P_TOCHOST                   1042
#define IDC_P_USERNAME                  1043
#define IDC_P_TOCUSERNAME               1043
#define IDC_P_PASSWORD                  1044
#define IDC_P_TOCPASSWORD               1044
#define IDC_P_RESETNETWORKDEFAULT       1045
#define IDC_P_ENABLEAIMCHATLOGGING      1047
#define IDC_RICHEDIT2                   1049
#define IDC_AWAYMESSAGEEDIT             1050
#define IDB_AWAYTOGGLE                  1051
#define IDC_GETINFOSTATUS               1053
#define IDC_LIST1                       1054
#define IDC_LOGDIR                      1055
#define IDC_IDLEMESSAGE                 1056
#define IDC_EDIT3                       1057
#define IDC_ADDNEWMESSAGE               1058
#define IDC_BUDDYLISTFONT               1059
#define IDC_ADDBLOCKEDBUDDY             1060
#define IDD_DIALOG1                     20000
#define ID_MIA_EXIT                     40001
#define ID_OPTIONS_CHANGEPASSWORD       40002
#define ID_MIA_LOADBUDDYLIST            40003
#define ID_MIA_LOADLIST                 40003
#define ID_MIA_SAVELIST                 40004
#define ID_ABOUT_ABOUTMIA               40006
#define ID_ABOUT_HELP                   40007
#define ID_ABOUT_FEEDBACK               40008
#define IDD_ABOUT_ABOUTJPONG            40009
#define ID_MIA_NEWCHATWINDOW            40009
#define ID_FILE_EXIT                    40010
#define ID_CHAT_FILE_EXIT               40010
#define ID_DEBUG_EXIT                   40010
#define ID_OPTIONS_BLOCKBUDDY           40011
#define ID_CHAT_OPTIONS_BLOCKBUDDY      40011
#define ID_OPTIONS_WARNBUDDY            40012
#define ID_CHAT_OPTIONS_WARNBUDDY       40012
#define ID_FILE_LOAD                    40014
#define ID_CHAT_FILE_LOAD               40014
#define ID_MIA_SIGNON                   40015
#define ID_MIA_STATUS_SIGNON            40015
#define ID_MIA_SIGNOFF                  40016
#define ID_MIA_STATUS_SIGNOFF           40016
#define ID_EXIT_SOMETHINGELSE           40017
#define ID_POPUP_MINIMIZE               40019
#define ID_MIA_MINIMIZEMAINWINDOW       40019
#define ID_POPUP_MAXIMIZE               40020
#define ID_MIA_SHOWMAINWINDOW           40020
#define ID_OPTIONS_OPENDEBUG            40021
#define ID_CHAT_FILE_SAVE               40022
#define IDC_DEBUG_VIEW                  40023
#define ID_MIA_DEBUGWINDOW              40024
#define ID_OPTIONS_EDITPROFILE          40025
#define ID_EDITINFO                     40025
#define ID_MIA_AWAYMESSAGE              40027
#define ID_MIA_EDITOPTIONS_PREFERENCES  40028
#define ID_POPUP_SIGNOFF                40029
#define ID_DEBUG_SAVEDEBUG              40030
#define ID_SAVE                         40030
#define ID_DEBUG_OPENDEBUG              40031
#define ID_LOAD                         40031
#define IDD_CSIGNONDLG                  40032
#define ID_TOP_MESSAGE                  40032
#define ID_TOP_GETINFO                  40033
#define ID_MIA_SHOWALLWINDOWS           40035
#define ID_MIA_CLOSEALLWINDOWS          40036
#define ID_MIA_MINIMIZEALLWINDOWS       40037
#define ID_MIA_AWAYMESSAGE_DEFAULTMESSAGE 40039
#define ID_TOP_ONLINETIME               40041
#define ID_TOP_IDLETIME                 40042
#define ID_TOP_GETUSERINFO              40043
#define ID_TOP_SENDMESSAGE              40044
#define ID_TOP_BLOCKBUDDY               40045
#define ID_TOP_COPYBUDDYNAMETOCLIPBOARD 40046
#define ID_TOP_SERVICE                  40047
#define ID_TOP_WARNINGLEVEL             40048
#define ID_TOP_BUDDYNAME                40049
#define ID_MIA_EDITOPTIONS_DELETEALLLOGFILES 40051
#define IDC_MENUBTN_ADDBUDDY            40052
#define ID_POP_OFFLINE                  40053
#define IDC_MENUBTN_ADDGROUP            40054
#define ID_POP_ONLINE                   40054
#define IDC_MENUBTN_REMOVE              40055
#define ID_POP_IDLE                     40055
#define ID_MIA_STATUS_IDLE              40055
#define IDC_MENUBTN_STATUS              40056
#define ID_POP_AWAY                     40056
#define IDC_MENUBTN_CLOSEALL            40057
#define ID_MIA_SIGNONSIGNOFF            40057
#define ID_MIA_WINDOWS_KEEPBUDDYLISTONTOP 40058
#define IDC_STATUS_EDIT                 40059
#define ID_TOP_INVITETOCHAT             40061
#define IDC_MENUBTN_CHATROOM            40459
#define IDC_EDIT_CHATROOMLIST           40559
#define ID_MIA_STATUS_AWAY              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         40062
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
